### ISSUE TITLE
Reduce logging frequency when limits are reached

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-docker#39]
If limits are reached SDA should probably not log things like this every single time:

"Error sending event to SPM {"error":"Limits reached, aborting request execution","errorId":"1794547510039","status":"403"}"

...could probably reduce logging this sort of stuff to logging at most every N minutes.

**Comment by megastef** [comment]
Docker creates exec events for container health checks, so the number of events was really high. 
This was the root cause of hitting the event limits. 

SDA was changed to ignore the exec/health checks  and failures of sending events go to SPM debug log, means such errors don't show up on console with the default production setting.
